// app.js
// QR 読み取り JS 生成ツール（フロントエンド叩き台）
// - 単純区切り / キー型 / 文字数型 の3モードを切り替え
// - フォーム入力から「ダミーのJSコード」を生成
// - .js ファイルとしてダウンロード

(function () {
  'use strict';

  // ---- ユーティリティ ----
  function $(selector) {
    return document.querySelector(selector);
  }
  function downloadJs(filename, source) {
    if (!source || !source.trim()) {
      alert('先に JSコードを生成してください。');
      return;
    }
    const blob = new Blob([source], { type: 'text/javascript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // ---- モード切り替え ----
  function setupModeSwitching() {
    const modeButtons = document.querySelectorAll('.mode-button');
    const wizards = {
      simple: $('#wizard-simple'),
      key: $('#wizard-key'),
      fixed: $('#wizard-fixed'),
    };
    const currentLabel = $('#current-mode-label');

    function activateMode(mode) {
      // ボタン表示
      modeButtons.forEach((btn) => {
        if (btn.dataset.mode === mode) {
          btn.classList.add('active');
        } else {
          btn.classList.remove('active');
        }
      });

      // ウィザード表示
      Object.entries(wizards).forEach(([key, el]) => {
        if (!el) return;
        if (key === mode) el.classList.add('active');
        else el.classList.remove('active');
      });

      // ラベル
      const labelMap = {
        simple: '単純区切り型',
        key: 'キー型',
        fixed: '文字数仕分け型',
      };
      currentLabel.textContent = labelMap[mode] || mode;
    }

    modeButtons.forEach((btn) => {
      btn.addEventListener('click', () => {
        const mode = btn.dataset.mode;
        activateMode(mode);
      });
    });

    // 初期モード
    activateMode('simple');
  }

  // ---- 単純区切り型：JS生成 ----
  function buildSimpleJs(config) {
    const { delimiter, tokenCount, memo } = config;
    const now = new Date().toISOString();

    return `// Generated by TANA-OROSHI Config Tool
// Mode: simple-delimiter
// Generated at: ${now}
// Delimiter: ${JSON.stringify(delimiter)}
// Token count: ${tokenCount}
${memo ? `// Memo: ${memo.replace(/\r?\n/g, ' ')}` : ''}

// ▼ ここに「単純区切り型」の本番ロジックを差し込みます。
//   - delimiter: 区切り文字
//   - tokenCount: トークン数

(function () {
  'use strict';

  const CONFIG = {
    mode: 'simple',
    delimiter: ${JSON.stringify(delimiter)},
    tokenCount: ${Number(tokenCount) || 0}
  };

  // TODO: 単純区切り型の kintone 用 JS をここに埋め込み
  //  - 既に作成済みの「単純区切りスキャナJS」をベースに
  //  - CONFIG を使って自動生成できるようにします。

  console.log('Simple mode CONFIG:', CONFIG);
})();`;
  }

  function setupSimpleWizard() {
    const delimiterInput = $('#simple-delimiter');
    const tokenCountInput = $('#simple-token-count');
    const memoInput = $('#simple-memo');
    const generateBtn = $('#simple-generate-btn');
    const downloadBtn = $('#simple-download-btn');
    const output = $('#simple-code-output');
    const status = $('#simple-status');

    generateBtn.addEventListener('click', () => {
      const delimiter = delimiterInput.value || ',';
      const tokenCount = Number(tokenCountInput.value || '0');

      if (!delimiter) {
        alert('区切り文字を入力してください。');
        return;
      }
      if (!tokenCount || tokenCount < 1) {
        alert('トークン数は 1 以上を指定してください。');
        return;
      }

      const js = buildSimpleJs({
        delimiter,
        tokenCount,
        memo: memoInput.value || '',
      });

      output.value = js;
      status.textContent = 'JSコードを生成しました。';
      downloadBtn.disabled = false;
    });

    downloadBtn.addEventListener('click', () => {
      downloadJs('pc-simple-scan.js', output.value);
    });
  }

  // ---- キー型：JS生成 ----
  function buildKeyJs(config) {
    const { separator, assignOp, mappingJson } = config;
    const now = new Date().toISOString();

    return `// Generated by TANA-OROSHI Config Tool
// Mode: key-value
// Generated at: ${now}
// Pair separator: ${JSON.stringify(separator)}
// Assign operator: ${JSON.stringify(assignOp)}

// キー → フィールド対応（ユーザー設定）
const KEY_MAPPING = ${mappingJson};

// ▼ ここに「キー型」の本番ロジックを差し込みます。
//   - KEY_MAPPING を使って a/b/c/d/e にマッピングします。

(function () {
  'use strict';

  const CONFIG = {
    mode: 'key',
    pairSeparator: ${JSON.stringify(separator)},
    assignOperator: ${JSON.stringify(assignOp)},
    mapping: KEY_MAPPING
  };

  // TODO: キー型の kintone 用 JS をここに埋め込み
  console.log('Key mode CONFIG:', CONFIG);
})();`;
  }

  function setupKeyWizard() {
    const separatorInput = $('#key-separator');
    const assignInput = $('#key-assign-operator');
    const mappingInput = $('#key-mapping-json');
    const generateBtn = $('#key-generate-btn');
    const downloadBtn = $('#key-download-btn');
    const output = $('#key-code-output');
    const status = $('#key-status');

    generateBtn.addEventListener('click', () => {
      const separator = separatorInput.value || ' ';
      const assignOp = assignInput.value || '=';
      const rawMapping = mappingInput.value.trim();

      if (!rawMapping) {
        alert('キー → フィールド対応（JSON）を入力してください。');
        return;
      }

      let parsed;
      try {
        parsed = JSON.parse(rawMapping);
      } catch (e) {
        alert('キー対応の JSON が不正です。構文を確認してください。');
        return;
      }

      const formattedJson = JSON.stringify(parsed, null, 2);
      const js = buildKeyJs({
        separator,
        assignOp,
        mappingJson: formattedJson,
      });

      output.value = js;
      status.textContent = 'JSコードを生成しました。';
      downloadBtn.disabled = false;
    });

    downloadBtn.addEventListener('click', () => {
      downloadJs('pc-key-scan.js', output.value);
    });
  }

  // ---- 文字数仕分け型：JS生成 ----
  function buildFixedJs(config) {
    const { schemaJson, memo } = config;
    const now = new Date().toISOString();

    return `// Generated by TANA-OROSHI Config Tool
// Mode: fixed-width
// Generated at: ${now}

// 固定長スキーマ（ユーザー設定）
const TOKEN_DEFS = ${schemaJson};
${memo ? `// Memo: ${memo.replace(/\r?\n/g, ' ')}` : ''}

// ▼ ここに「文字数仕分け型」の本番ロジックを差し込みます。
//   - TOKEN_DEFS を使って先頭から順に切り出します。

(function () {
  'use strict';

  const CONFIG = {
    mode: 'fixed',
    tokenDefs: TOKEN_DEFS
  };

  // TODO: 文字数仕分け型の kintone 用 JS をここに埋め込み
  console.log('Fixed width CONFIG:', CONFIG);
})();`;
  }

  function setupFixedWizard() {
    const schemaInput = $('#fixed-schema');
    const memoInput = $('#fixed-memo');
    const generateBtn = $('#fixed-generate-btn');
    const downloadBtn = $('#fixed-download-btn');
    const output = $('#fixed-code-output');
    const status = $('#fixed-status');

    generateBtn.addEventListener('click', () => {
      const rawSchema = schemaInput.value.trim();
      if (!rawSchema) {
        alert('スキーマ定義（JSON）を入力してください。');
        return;
      }

      let parsed;
      try {
        parsed = JSON.parse(rawSchema);
      } catch (e) {
        alert('スキーマ定義の JSON が不正です。構文を確認してください。');
        return;
      }
      if (!Array.isArray(parsed)) {
        alert('スキーマ定義は配列（[]）で指定してください。');
        return;
      }

      const formattedJson = JSON.stringify(parsed, null, 2);
      const js = buildFixedJs({
        schemaJson: formattedJson,
        memo: memoInput.value || '',
      });

      output.value = js;
      status.textContent = 'JSコードを生成しました。';
      downloadBtn.disabled = false;
    });

    downloadBtn.addEventListener('click', () => {
      downloadJs('pc-fixedwidth-scan.js', output.value);
    });
  }

  // ---- 初期化 ----
  document.addEventListener('DOMContentLoaded', () => {
    setupModeSwitching();
    setupSimpleWizard();
    setupKeyWizard();
    setupFixedWizard();
  });
})();
